//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentArchive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterStorage
    {
        public int Id { get; set; }
        public int FileInfoId { get; set; }
        public string Keyword { get; set; }
        public int DescriptionId { get; set; }
        public int CategoryId { get; set; }
        public int TextSearchingId { get; set; }
        public int IndexSearching { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual FileInfo FileInfo { get; set; }
        public virtual TextSearching TextSearching { get; set; }
    }
}
