//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentArchive.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectronicDocumentArchiveEntities : DbContext
    {
        public ElectronicDocumentArchiveEntities()
            : base("name=ElectronicDocumentArchiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Description> Description { get; set; }
        public virtual DbSet<FileAccessLevel> FileAccessLevel { get; set; }
        public virtual DbSet<FileInfo> FileInfo { get; set; }
        public virtual DbSet<FilterStorage> FilterStorage { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TextSearching> TextSearching { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserFile> UserFile { get; set; }
        public virtual DbSet<GuestFileInfo> GuestFileInfo { get; set; }
    }
}
