//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentArchive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestFileInfo
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public string ShareLink { get; set; }
        public int AccessLevelId { get; set; }
        public Nullable<bool> IsPinned { get; set; }

		public string DocImg
		{
			get
			{
				if (Title.EndsWith(".pdf"))
				{
					return @"/Resources/pdfLogo.png";
				}
				else if (Title.EndsWith(".docx"))
				{
					return @"/Resources/docxLogo.png";
				}
				else
				{
					return string.Empty;
				}
			}
		}
	}
}
