//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentArchive.Model.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageHistory
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FileInfoId { get; set; }
        public System.DateTime DateUpload { get; set; }
        public int StatusId { get; set; }
    
        public virtual FileInfo FileInfo { get; set; }
        public virtual StatusUpload StatusUpload { get; set; }
        public virtual User User { get; set; }
    }
}
